---
- name: Valuable configs
  setup: gather_subset='network'

- name: Disallow password Authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^#?PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: "restart ssh"

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^#?PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: "restart ssh"

- name: Create Match  for exemptions
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker:
      "# {mark} ANSIBLE MANAGED BLOCK Match address {{item.id}}"
    block: |
      Match address {{ item.addr }}
              PermitRootLogin without-password
              PasswordAuthentication yes
    state: "{{ item.state }}"
  with_items:
    "{{ privileged_host }}"
  notify: "restart ssh"
...