---
- name: Valuable configs
  setup: gather_subset='network'

- name: Modify "{{ hosts_file }}"
  lineinfile: dest="{{ hosts_file }}"
              regexp="{{ item.ip }}.*"
              line="{{ item.ip }}\t{{ item.name }}"
              state="{{ item.state }}"
              owner=root
              group=root
              mode=0644
  with_items:
    - "{{ hosts_mappings }}"

- name: Modify "{{ hostname_file }}"
  lineinfile: dest="{{ hostname_file }}"
              line="{{ hostname }}"
              regexp='\s+'
              owner=root
              group=root
              mode=0644

- name: Change Hostname
  hostname:
    name: "{{ hostname }}"
...
