---
- name: Valuable configs
  setup: gather_subset='network'

- name: Modify "{{ hosts_file }}"
  lineinfile: dest="{{ hosts_file }}"
              regexp="{{ item.regexp }}"
              line="{{ item.ip }}\t{{ item.name }}"
              state="{{ item.state }}"
              owner=root
              group=root
              mode=0644
  with_items:
    - "{{ custom_hosts }}"

- name: Modify "{{ hostname_file }}"
  lineinfile: dest="{{ hostname_file }}"
              line="{{ custom_hostname }}"
              regexp='\s+'
              owner=root
              group=root
              mode=0644
              # TODO Overwrite /etc/hostname

- name: Change Hostname
  hostname:
    name: "{{ custom_hostname }}"
...