---
- hosts: 127.0.0.1
  gather_facts: false
  roles:
    - manage-ssh-known_hosts

- hosts: all
  become: true
  gather_facts: False
  vars:
  roles:
    - install-python
    - manage-packages
    - manage-iptables
    - manage-ssh-keys
    - manage-network-configuration
    - manage-sshd-configuration
  tasks:
    - name: reboot the system when playbook is applied
      command: /sbin/shutdown -r 1 "Ansible Calling for a System Reboot"
...
