---
- name: Add RPM Repository Key for Saltstack
  yum:
    name: "https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: installed

- name: Install Saltstack Minion
  yum:
    update_cache: yes
    name: salt-minion
    state: latest
  when: SALT_MINION_FLAG == True

- name: Install Saltstack Master
  yum:
    update_cache: yes
    name: salt-master
    state: latest
  when: SALT_MASTER_FLAG == True
...