---
- name: Enable and Start Salt Service (Systemd)
  systemd:
    daemon_reload: yes
    state: started
    name: "{{ item.name }}"
  with_items:
    - '{{ salt_packages }}'
  when: ansible_service_mgr == "systemd" and item.state != "absent"

- name: Enable and Start Salt Service (Upstart)
  service:
    enabled: yes
    state: started
    name: "{{ item.name }}"
  with_items:
    - '{{ salt_packages }}'
  when: ansible_service_mgr == "upstart" and item.state != "absent"

- name: Configure Salt-Master
  template: src="{{ SALT_MASTER_CONFIG }}" dest="/etc/salt/master" force=yes backup=yes owner=root group=root mode=0644
  when: SALT_MASTER_FLAG == True
  notify: "master-restart"

- name: Configure Salt-Minion
  template: src="{{ SALT_MINION_CONFIG }}" dest="/etc/salt/minion" force=yes backup=yes owner=root group=root mode=0644
  when: SALT_MINION_FLAG == True
  notify: "minion-restart"
...