---
- name: Grab Facts
  setup: gather_subset='all'

- name: Include "{{ ansible_os_family }}" Tasks -> INSTALL
  include: "{{ ansible_os_family }}.yml"

#- name: Include "{{ ansible_os_family }}" Tasks -> UNINSTALL
#  include: "remove{{ ansible_os_family }}.yml"
#  when: UNINSTALL_FLAG == True
...