---
- name: Grab Facts
  setup: gather_subset='all'

- name: Include "{{ ansible_distribution }}" INSTALL TASKS
  include: "{{ ansible_distribution }}.yml"
  # WIP include per OS distribution to cover Debian vs Ubuntu
  # Possibly use os_family to stack usage of same package manager
  when: SALT_INSTALL_FLAG == True

- name: Include CONFIGURE Tasks
  include: configure.yml
  when: SALT_CONFIGURE_FLAG == True
...