---
- name: Restart ssh Debian Based
  service: name=ssh state=reloaded
  listen: "restart ssh"
  when: (ansible_os_family == "Debian") or  (ansible_os_family == "Ubuntu")

- name: Restart ssh CentOS Based
  service: name=sshd state=reloaded
  listen: "restart ssh"
  when: ansible_distribution == "CentOS"

- name: Restart ssh BSD Based
  service: name=ssh state=reloaded
  listen: "restart ssh"
  when: ansible_distribution == "FreeBSD"
...