---
# defaults vars file for manage-ssh-keys
ssh_vars:
  - username: root
    state: present
    keys:
      - ""

  - username: "{{ ansible_user | default('{{ ansible_user_id }}') }}"
    state: present
    keys:
      - ""
...
