---
- name: Uninstall filebeat package
  yum:
    name: "{{ item.beatname }}"
    state: absent
  with_items:
    - '{{ beats_config }}'
  when: UNINSTALL_FLAG == True

- name: Remove /etc/filebeat
  file:
    path: "/etc/filebeat"
    state: absent
  when: UNINSTALL_FLAG == True


- name: Remove /var/lib/filebeat
  file:
    path: "/var/lib/filebeat"
    state: absent
  when: UNINSTALL_FLAG == True
...