---
iface: "{{ ansible_default_ipv4.interface }}"

RELOAD_FLAG: False

rules_v4_template: "base_secure_rules.v4.j2"
rules_v6_template: "base_secure_rules.v6.j2"

rules_v4_dest: "/etc/iptables/rules.v4"
rules_v6_dest: "/etc/iptables/rules.v6"

trusted_subnet:
trusted_host:

trusted_subnets_list:
  - "{{ trusted_subnet }}"

trusted_hosts_list:
  - "{{ trusted_host }}"

public_services:
  - port: 4505
    service: "salt"
    protocol: tcp
    iface: "{{ iface }}"
    direction: "out"

  - port: 4506
    service: "salt"
    protocol: tcp
    iface: "{{ iface }}"
    direction: "out"

restricted_services:
  - port: 333333
    service: ""
    protocol: tcp
    iface: "{{ iface }}"
    sources:
      - "83.212.121.12"
      - "83.212.100.68"
      - "83.212.96.122"
      - "83.212.102.222"
      - "83.212.105.172"

  - port: 22
    service: "ssh"
    protocol: tcp
    iface: "{{ iface }}"
    sources:
      - "83.212.121.12"
      - "83.212.100.68"
      - "83.212.96.122"
      - "83.212.102.222"
      - "83.212.105.172"

  - port: 123
    service: "ntp"
    protocol: udp
    iface: "{{ iface }}"
    sources:
      - "83.212.121.12"
      - "83.212.100.68"
      - "83.212.96.122"
      - "83.212.102.222"
      - "83.212.105.172"

subnet_services:
...