---
trusted_subnet:
trusted_host:

trusted_subnets_list:
	- "{{ trusted_subnet }}"

trusted_hosts_list:
	- "{{ trusted_host }}"

public_services: 22
subnet_services:
host_services:
  - 8080
  - 53
...