---
iface: "{{ ansible_default_ipv4.interface }}"

ALLOW_OUT: False
RELOAD_FLAG: False

rules_v4_template: "base_secure_rules.v4.j2"
rules_v6_template: "base_secure_rules.v6.j2"

rules_v4_dest_deb: "/etc/iptables/rules.v4"
rules_v6_dest_deb: "/etc/iptables/rules.v6"
rules_v4_dest_rh: "/etc/sysconfig/iptables"
rules_v6_dest_rh: "/etc/sysconfig/ip6tables"

trusted_subnet:
trusted_host:

trusted_subnets_list:
  - "{{ trusted_subnet }}"

trusted_hosts_list:
  - "{{ trusted_host }}"

public_services:
#  - port: 123
#    service: "ntp"
#    protocol: udp
#    iface: "{{ iface }}"
#    direction: "in"

restricted_services:
#  - port: 22
#    service: "ssh"
#    protocol: tcp
#    iface: "{{ iface }}"
#    sources:
#      - "sourceA"
#      - "sourceB"
#      - "sourceC"

subnet_services:
...