---
- name: Grab active interface
  setup: gather_subset='network'

- name: Generate UUID
  raw: uuidgen "{{ primary_interface }}"
  register: iface_uuid

- name: Create Base Configuration
  template: src="{{ redhat_template }}" dest="{{ redhat_config }}" force=yes backup=yes owner=root group=root mode=0644
...
