---
- name: Grab Facts
  setup: gather_subset='all'

- name: Include "{{ ansible_os_family }}"
  include: "{{ ansible_os_family }}.yml"

- name: Include "{{ ansible_os_family }}"
  include: "{{ ansible_os_family }}.yml"
...
