---
- name: Install iptables-services
  yum:
    update_cache: yes
    name: "iptables-services"
    state: latest

- name: Disable and Stop firewalld
  systemd:
    name: "firewalld"
    state: "stopped"
    enabled: "no"

- name: Enable and Start iptables.service
  systemd:
    name: "iptables.service"
    state: "started"
    enabled: "yes"

# Load the Templates
- name: Load IPv4 iptables rules
  template: src="{{ rules_v4_template }}" dest="{{ rules_v4_dest_rh }}" force=yes backup=yes owner=root group=root mode=0644
  notify: "iptables-restore"

- name: Load IPv6 iptables rules
  template: src="{{ rules_v6_template }}" dest="{{ rules_v6_dest_rh }}" force=yes backup=yes owner=root group=root mode=0644
  notify: "ip6tables-restore"

- meta: flush_handlers
...
