---
interfaces:
- ipv4: "{{ primary_ip }}"
  netmask: "{{ primary_netmask }}"
  network: "{{ primary_network }}"
  broadcast: "{{ primary_broadcast }}"
  dns: "{{ primary_dns1 }} {{ primary_dns2 }}"
  gateway: "{{ gateway }}"
  iface: "{{ primary_interface }}"

primary_ip: ""
primary_netmask: ""
primary_network: ""
primary_broadcast: ""
primary_dns1: ""
primary_dns2: ""
gateway: ""
primary_interface: "{{ ansible_default_ipv4.alias }}"
#primary_interface: "{{ ansible_interfaces.0 }}"
config: "{{ debian_config }}"
template: "{{ debian_template }}"
debian_config: "/etc/network/interfaces"
debian_template: "debian-network-base-cfg.j2"
redhat_config: "/etc/sysconfig/network-scripts/ifcfg-{{ primary_interface }}"
redhat_template: "redhat-network-base-cfg.j2"
...
