---
# source:http://ryaneschinger.com/blog/securing-a-server-with-ansible/

- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Install Logwatch
      apt: name=logwatch state=latest update_cache=yes

    - name: Set up Postfix to relay mail
      debconf: name=postfix 
               question= "{{item.question}}"
               value= "{{item.value}}"
               vtype= "{{item.vtype}}"   
      with_items:
        - { question: "postfix/mailname", value: "{{ansible_fqdn}}", vtype: "string" }
        - { question: "postfix/main_mailer_type", value: "Internet Site", vtype: "string" }

    - name: Email Logs Daily
      lineinfile: dest=/etc/cron.daily/00logwatch
                  regexp= "^/usr/sbin/logwatch"
                  line= "/usr/sbin/logwatch --output mail --mailto {{ LOGWATCH_EMAIL }} --detail high"
                  state=present create=yes
