---
- include: ssh-keys.yml
- hosts: all
  tasks:
    - name: Print Facts
      debug: var=ansible_all_ipv4_addresses

- include: upd-upgr.yml
#- include: network-gather.yml
- include: network-cfg.yml
#- include: hostname.yml
#- include: ssh-cfg.yml
- include: firewall.yml
...
