---
- hosts: all
  tasks:
    - name: List all Available Interfaces
      debug: var=ansible_interfaces

    #- name: Select interface to view available info
    #  prompt: "Select an Interface to view appropriate information"

    - name: Create Base Configuration
# TODO Change test-base.conf to /etc/network/interfaces
      template: src=templates/network-base-cfg.j2 dest=~/test-base.conf
      when: append_flag=="No"

    - name: Extend Base Configuration
      template: src=templates/network-append-cfg.j2 dest=~/test-append.conf
      when: append_flag!="No"
      notify: Append Configuration

  handlers:
    - name: Append Configuration
# TODO Change test-base.conf to /etc/network/interfaces
      shell: cat ~/test-append.conf >> test-base.conf     
      notify: Restart Network

    - name: Restart Network
      command: bash -c "sudo ifdown {{iface}} && sudo ifup {{iface}}"

#    - name: Restart Network Configuration
#      Use the shell ifdown-ifup
# Prompt User for IPs?
  vars_prompt:
    - name: "iface"
      prompt: "Please Select the Network Interface you want to create the configuration for"
      default: "eth0"
    
    - name: "append_flag"
      prompt: "Append to already existing config?"
      default: "No"

    - name: "desired_IP"
      prompt: "Please Input the desired IP Address"

    - name: "desired_MASK"
      prompt: "Please Input the desired Network Mask"
      default: "255.255.255.0"

    - name: "desired_NETWORK"
      prompt: "Please Input the desired Network Address"

    - name: "desired_BROADCAST"
      prompt: "Please Input the desired Broadcast Address"

      # TODO Add functionality for Default DNS based on Groups
    - name: "desired_DNS"
      prompt: "Please Enter the desired DNS Servers"
      default: "8.8.8.8"

    - name: "desired_GATEWAY"
      prompt: "Please Enter the desired default Gateway"
...
