---
- hosts: all
  tasks:
    - name: List all Available Interfaces
      debug: var=ansible_interfaces

    #- name: Select interface to view available info
    #  prompt: "Select an Interface to view appropriate information"

    - name: Create Template
      template: src=templates/network-base-cfg.j2 dest=~/test.conf

#    - name: Restart Network Configuration
#      Use the shell ifdown-ifup
# Prompt User for IPs?
  vars_prompt:
    - name: "iface"
      prompt: "Please Select the Network Interface you want to create the configuration for"
      default: "eth0"
    
    - name: "append_flag"
      prompt: "Append to already existing config?"
      default: "No"

    - name: "desired_IP"
      prompt: "Please Input the desired IP Address"
      default: "{{ansible_default_ipv4.address}}"

    - name: "desired_MASK"
      prompt: "Please Input the desired Network Mask"
      default: "{{ansible_default_ipv4.netmask}}"

    - name: "desired_NETWORK"
      prompt: "Please Input the desired Network Address"
      default: "{{ansible_default_ipv4.network}}"

    - name: "desired_BROADCAST"
      prompt: "Please Input the desired Broadcast Address"
      default: "{{ansible_default_ipv4.broadcast}}"

      # TODO Add functionality for Default DNS based on Groups
    - name: "desired_DNS"
      prompt: "Please Enter the desired DNS Servers"
      default: "{{ansible_dns}}"

    - name: "desired_GATEWAY"
      prompt: "Please Enter the desired default Gateway"
      default: "{{ansible_default_ipv4.gateway}}"
...
