---
- hosts: all
  become: yes
  tasks:
    - name: Enable Root Login with SSH
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^#?PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^#?PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present

    - name: Test for exemptions
      shell: grep -P '^Match' /etc/ssh/sshd_config
      register: test_match
      failed_when: test_match.rc != 0 and test_match.stdout != ""

    - name: Append exemptions
      shell: echo "Match address 147.102.13.0/24\n\tPermitRootLogin without-password\n\tPasswordAuthentication yes" >> /etc/ssh/sshd_config
      when: test_match.stdout == ""
      notify: Restart ssh

      # Use Specific Hosts both in REGEX as well as Exemption
    - name: Replace Exemptions
      replace: 
        dest=/etc/ssh/sshd_config
        regexp="Match.+\n.+\n.*\n?"
        replace="Match address 147.102.13.0/24\n\tPermitRootLogin without-password\n\tPasswordAuthentication yes\n"
        force=yes
      when: test_match.stdout != ""
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
...
